server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl11
    driver-class-name: oracle.jdbc.OracleDriver
    username: mblog
    password: mblog
    hikari:
      connection-timeout: 20000
      validation-timeout: 3000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: true
      pool-name: oraPool
  servlet:
    multipart:
      enabled: true